name: multisig wallet ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-multisig-wallet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Starting Bitcoin Core in regtest
        run: |
          echo "starting bitcoin core in regtest ✌️"
          docker run -d \
          --name bitcoind-regtest \
          -p 18443:18443 \
          -p 18444:18444 \
          ruimarinho/bitcoin-core:alpine \
          -regtest \
          -server \
          -rpcbind=0.0.0.0:18443 \
          -rpcallowip=0.0.0.0/0 \
          -rpcuser=abhishek \
          -rpcpassword=abhishek \
          -rpcport=18443 \
          -printtoconsole \
          -txindex \
          -fallbackfee=0.0002 \
          -acceptnonstdtxn=1
      
      - name: Wait for bitcoin core to start
        run: |
          echo "waiting for bitcoin core to be ready ...."
          
          for i in {1..20}; do
            if docker exec bitcoind-regtest bitcoin-cli \
                -regtest \
                -rpcuser=abhishek \
                -rpcpassword=abhishek \
                getblockchaininfo >/dev/null 2>&1; then
              echo "Bitcoin core is readyyy"
              break
            fi
            echo "attempt: $i/20 | bitcoin core starting again 3 2 1 ... lets gooo"
            sleep 3
          done

          echo "Bitcoin core status"
          docker exec bitcoind-regtest bitcoin-cli \
            -regtest \
            -rpcuser=abhishek \
            -rpcpassword=abhishek \
            getblockchaininfo | grep -E '(chain|blocks|bestblockhash)'

        
      - name: Build typescript
        run: npm run build
      
      - name: run multisig wallet test
        run: npm start
        env:
          NODE_ENV: test
      
      - name: Showing bitcoin core logs
        if: failure()
        run: |
          echo "Bitcoin core logs" 
          docker logs --tail 50 bitcoind-regtest
      
      - name: CleanUp bitcoin container
        if: always()
        run: |
          echo "removing bitcoind-regtest container"
          docker stop bitcoind-regtest || true
          docker rm bitcoind-regtest || true
      

      - name: CI results hehee 
      #here like for now lets be always but this shoudl not be ig always (like on failure)
        if: always()
        run: |
          echo "<--test summary-->"
          echo "bitcoin Core regtest service started"
          echo "nodejs installed successfully"
          echo "Multisig wallet operations completed"
          echo "CI pipeline completedd"

            



      

