name: multisig wallet ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-multisig-wallet:
    runs-on: ubuntu-latest

    services:
      #bitcoin core 
      #starting with container name
      bitcoind:
        image: ruimarinho/bitcoin-core:alpine
        ports:
          - 18443:18443 #rpc port
          - 18444:18444 #p2p port
        options: >-
          --health-cmd "bitcoin-cli -regtest -rpcuser=abhishek -rpcpassword=abhishek -rpcport=18443 getblockchaininfo || exit 1"
          --health-interval 15s
          --health-timeout 10s
          --health-retries 20
          -regtest=1
          -server=1
          -rpcbind=0.0.0.0:18443
          -rpcallowedip=0.0.0.0/0
          -rpcuser=abhishek
          -rpcpassword=abhishek
          -rpcport=18443
          -printtoconsole=1
          -txindex=1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Wait for bitcoin core to be ready
        run: |
          echo "waiting for bitcoin core to start"
          # checkign first the rpc connectivity if avail at port localhost:18443
          for i in {1..30}; do
            if curl -s --data-binary '{"jsonrpc":"1.0", "id":"test","method":"getblockchaininfo","params":[]}' \
               -H "Content-Type: application/json" \
               -u "abhishek:abhishek" \
               http://127.0.0.1:18443/; then
              echo "Bitcoin core RPC is responding now.."
              break
            fi
            echo "attempt $i: bitcoin core is not ready yet, waittt"
            sleep 2
          done

      - name: verify the bitcoin core configuration
        run: |
          echo "testing bitcoin core RPC connection firstt"
          # for now using curl instead of bitcoin-cli (as that one not installed yet hehe)
          response=$(curl -s --data-binary '{"jsonrpc":"1.0","id":"test","method":"getblockchaininfo","params":[]}' \
                     -H "Content-Type: application/json" \
                     -u "abhishek:abhishek" \
                     http://127.0.0.1:18443/ )
          echo "Bitcoin core res: $response"

          if echo "$response" | grep -q '"chain":"regtest"'; then 
            echo "Bitcoin core runnninggg 😊 :))"
          else
            echo "Bitcoin core is not in regtest mode or not responding 😭"
            exit 1
          fi 

      - name: Build typescript
        run: npm run build
      
      - name: run multisig wallet test
        run: npm start
        env:
          NODE_ENV: test
      
      - name: lets verify test results
        run: |
          echo "multisig wallet test completed successfully"
          # will add more verifcation here like if some files are created or not or check for some logs 

      - name: displaying test results
        if: always()
        run: |
          echo "<--test summary-->"
          echo "bitcoin Core regtest service started"
          echo "nodejs installed successfully"
          echo "Multisig wallet operations completed"

            



      

