name: multisig wallet ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  test-multisig-wallet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Starting Bitcoin Core in regtest
        run: ./scripts/start_bitcoin_regtest.sh
      
      - name: Wait for bitcoin core to start
        run: ./scripts/wait_btccore_tostart.sh

        
      - name: Build typescript
        run: npm run build
      
      - name: run multisig wallet test
        run: npm start
        env:
          NODE_ENV: test
      
      - name: Showing bitcoin core logs
        if: failure()
        run: ./scripts/show_docker_logs.sh
      
      - name: CleanUp bitcoin container
        if: always()
        run: ./scripts/cleanup_container.sh
      

      - name: CI results hehee 
      #here like for now lets be always but this shoudl not be ig always (like on failure)
        if: always()
        run: |
          echo "<--test summary-->"
          echo "bitcoin Core regtest service started"
          echo "nodejs installed successfully"
          echo "Multisig wallet operations completed"
          echo "CI pipeline completedd"

            



      

